name: GitHub Action
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "my github action"
      - name: list files
        run: |
          ls ${{ github.workspace }}
      - run: job status is ${{ job.status }}
